### ISSUE TITLE
#2 - Review

### ISSUE THREAD

**Issue by Marcosreuquen** [giulianaerro/online-piedra-papel-tijera#2]
Giuli, 

Los dos temas centrales son la page de share-code y cuando uno de los jugadores no elije.

Lo que podrías hacer en la page share-code es, en vez de darle el botón de continuar, como para que se entere el jugador que el otro ya está es englobar todo el código que está dentro del connectedCallback() dentro de un suscribe y luego, debajo de eso hacerle que renderice por primera vez. 

https://github.com/giulianaerro/online-piedra-papel-tijera/blob/055403b3f28475ec3bb26483905621f20b6db7d1/client/pages/share-code/index.ts#L6-L9

Después como este jugador ya tiene el roomId de la rtdb podría conectarse y en vez de tener las dos funciones que la escuchan 
https://github.com/giulianaerro/online-piedra-papel-tijera/blob/055403b3f28475ec3bb26483905621f20b6db7d1/client/pages/waiting-rival-page/index.ts#L10
https://github.com/giulianaerro/online-piedra-papel-tijera/blob/055403b3f28475ec3bb26483905621f20b6db7d1/client/pages/play-move/index.ts#L32 
Tener una sola función que guarde todo lo que trae la rtdb en el state y de ahí validarlo. Estarías conectando el state con la rtdb, y las pages validarian sólo lo que hay en el state. Y esto sucedería cada vez que cambia el estado y con englobar el render en un subscribe, te enterarías en la page siempre. Con eso podrías ver si necesitas seguir en esa page o ya te podés pasar a la siguiente.

Sobre lo otro, me parece que debe pasar algo en la siguiente línea.

https://github.com/giulianaerro/online-piedra-papel-tijera/blob/055403b3f28475ec3bb26483905621f20b6db7d1/client/pages/play-move/index.ts#L86

![image](https://user-images.githubusercontent.com/75027556/141022421-e5db217c-3a8a-4568-a3a0-42588d8f6839.png)

Me parece que de alguna forma el rival no guarda su elección "vacía" como `"none"` sino como un string vacío.
Debe ser por ahí la cosa.

Espero haberte ayudado más de lo que te enquilombé jaja.
Saludooos!!

**Comment by giulianaerro** [comment]
gracias por la ayuda marcosssss!
